services:
  btn-game:
    build: .
    volumes: 
      - /var/log/vinskis-great-button-game/gunicorn/:/var/log/gunicorn/
      - /home/lauri/sqlite/button-game.db:/usr/src/app/button-game.db
    networks:
      - nginx

networks:
  nginx:
    name: nginx
    external: true
